### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [gusye1234/Gus-zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by gusye1234** [comment]
Thanks for your interests!
Just want to make this as easy as possible to you, so if any license you prefer, please inform me. 
Notice awesome-zag-plugin is using BSD, so my default choice will be this license too.
